services:
  db:
    ports:
      - "5432:5432"  # Open DB to host for DBeaver/IntelliJ

  backend:
    ports:
      - "8080:8080"  # Open Backend for Postman/Curl
    environment:
      # Dev logging is verbose
      LOGGING_LEVEL_ROOT: DEBUG

  frontend:
    ports:
      - "3000:3000"  # Open Frontend for Browser
    volumes:
      # HOT RELOADING: Syncs your code changes instantly
      - ./frontend:/app
      - /app/node_modules
      - /app/.next