spring:
  application:
    name: note-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/note_db}
    username: ${SPRING_DATASOURCE_USERNAME:note_user}
    password: ${SPRING_DATASOURCE_PASSWORD:note_password}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

  output:
    ansi:
      enabled: ALWAYS
app:
  file:
    storage:
      path: /home/ojasva/Prod/self-hosted-notes/uploads
      #path: /home/ojasva/Projects/self-hosted-notes/uploads
  lock:
    password: ${LOCK_PASSWORD:finalXV}
