spring:
  application:
    name: note-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/notedb}
    username: ${SPRING_DATASOURCE_USERNAME:note_user}
    password: ${SPRING_DATASOURCE_PASSWORD:password@123}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

app:
  file:
    storage:
      path: ${APP_FILE_STORAGE_PATH:/tmp/uploads}
  lock:
    password: ${LOCK_PASSWORD:finalXV}